[general]

# Start Satty in fullscreen mode
fullscreen = false

# Exit directly after copy/save action
early-exit = false

# Draw corners of rectangles round if the value is greater than 0
# 0 disables rounded corners
corner-roundness = 0

# Select the tool on startup
# [possible values: pointer, crop, line, arrow, rectangle,
# text, marker, blur, brush]
initial-tool = "crop"

# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"

# Increase or decrease the size of the annotations
annotation-size-factor = 2

# Filename to use for saving action.
# Omit to disable saving to file.
# Can contain format specifiers:
# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
output-filename = "/tmp/test-%Y-%m-%d_%H:%M:%S.png"

# After copying the screenshot, save it to a file as well
save-after-copy = false

# Hide toolbars by default
default-hide-toolbars = false

# Experimental: whether window focus shows/hides toolbars.
# This does not affect initial state of toolbars, see default-hide-toolbars.
focus-toggles-toolbars = false

# Fill shapes by default
default-fill-shapes = true

# The primary highlighter to use,
# the other is accessible by holding CTRL
# at the start of a highlight [possible values: block, freehand]
primary-highlighter = "block"

# Disable notifications
disable-notifications = false

# Actions to trigger on right click (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-right-click = []

# Actions to trigger on Enter key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-enter = ["save-to-clipboard"]

# Actions to trigger on Escape key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-escape = ["exit"]

# Request no window decoration.
# Please note that the compositor has the final say in this.
# At this point. Requires xdg-decoration-unstable-v1.
no-window-decoration = true

# Experimental feature: adjust history size for brush input smoothing
# (0: disabled, default: 0, try e.g. 5 or 10)
brush-smooth-history-size = 10

# Tool selection keyboard shortcuts
[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"

# Custom colours for the colour palette
[color-palette]

# These will be shown in the toolbar for quick selection
palette = ["#ffffff", "#000000", "#ff0000", "#ffd700", "#008000", "#0000ff"]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = []
