# Schema
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Bluloco dark flavour for Yazi
[manager]

cwd = { fg = "#3691FF" }

marker_copied = { fg = "#F9C858", bg = "#F9C858" }
marker_cut = { fg = "#FF6480", bg = "#FF6480" }
marker_marked = { fg = "#9F7EFE", bg = "#9F7EFE" }
marker_selected = { fg = "#10B1FE", bg = "#10B1FE" }

count_copied = { fg = "#282C34", bg = "#F9C858" }
count_cut = { fg = "#282C34", bg = "#FF6480" }
count_selected = { fg = "#282C34", bg = "#10B1FE" }

tab_active = { fg = "#3691FF", bg = "#3A3F4B" }
tab_inactive = { fg = "#5F697C", bg = "#2C313A" }

[manager.find_keyword]
fg = "#E3B80D"
bg = "#1A7247"
bold = true
italic = true
underline = true

[manager.find_position]
fg = "#ABB2BF"
bg = "reset"
bold = true
italic = true


# Colours for the modes in Yazi.
#
# The main styles are the styles for
# sections at the ends of the status bar.
#
# The alternate styles (alt) are the
# styles for the separators, which are
# the sections in the status bar
# that are right beside the sections
# at the ends of the status bar.
[mode]
normal_main = { fg = "#282C34", bg = "#10B1FE" }
normal_alt = { fg = "#8691A3", bg = "#384252" }

select_main = { fg = "#282C34", bg = "#9F7EFE" }
select_alt = { fg = "#9F7EFE", bg = "#384252" }

unset_main = { fg = "#282C34", bg = "#FF6480" }
unset_alt = { fg = "#FF6480", bg = "#384252" }


[status]
progress_label = { fg = "#282C34", bold = true }
progress_normal = { fg = "#9F7EFE", bg = "#636D83" }
progress_error = { fg = "#FF2E3F", bg = "#FDCFD1" }


[pick]
border = { fg = "#7A82DA" }
active = { fg = "#F9C859", bold = true }

[input]
border = { fg = "#7A82DA" }
title = { fg = "#7A82DA" }


[confirm]
border = { fg = "#7A82DA" }
title = { fg = "#7A82DA" }
btn_yes = { fg = "#3FC56B" }
btn_no = { fg = "#FF6480" }
btn_labels = ["Yes", "No"]


[spot]
border = { fg = "#7A82DA" }
title = { fg = "#7A82DA" }


[completion]
border = { fg = "#7A82DA" }
active = { bg = "#274670" }


[tasks]
border = { fg = "#7A82DA" }
title = { fg = "#7A82DA" }
hovered = { bg = "#274670", bold = true }


[which]
cand = { fg = "#FF936A" }
mask = { bg = "#21232C" }
desc = { fg = "#10B1FE" }
separator_style = { fg = "#7A82DA" }


[help]
on = { fg = "#FF936A" }
run = { fg = "#10B1FE" }
desc = { fg = "#ABB2BF" }
footer = { bg = "#282C34", fg = "#ABB2BF" }


[notify]
title_info = { fg = "#3691FF" }
title_warn = { fg = "#DA7A43" }
title_error = { fg = "#FF2E3F" }
