#:schema https://yazi-rs.github.io/schemas/theme.json

# Use the theme that I want
[flavor]
light = "bluloco-light"
dark = "bluloco-dark"

# Remove the borders
[mgr]
border_symbol = " "

# Set the outer separators
[tabs]
sep_outer = { open = "█", close = "█" }

# Set the status separators
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Set the icons for the notifications
[notify]
icon_info = ""
icon_warn = ""
icon_error = ""

# Set the icons for the completion
[cmp]
icon_file = "󰈙"
icon_folder = "󰉋"
icon_command = ""

# Set the icons for the git plugin
[git]
modified_sign = ""
added_sign = ""
untracked_sign = "󱋽"
ignored_sign = ""
deleted_sign = ""

# Unmerged
updated_sign = ""
