# Schema
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# Configurations for the file manager
[mgr]

# Ratio for the panes in the file manager
# This follows the lf configuration
ratio = [1, 2, 3]

# Sort naturally
sort_by = "natural"

# Show directories first
sort_dir_first = true

# Show hidden files
show_hidden = true

# Set the scroll offset to 8 from the bottom and top
scrolloff = 8


# Configuration for the file previewer
[preview]

# Wrap long lines for text previews
wrap = "yes"

# Make the maximum size of the images larger
max_width = 3000
max_height = 3000


# Configuration for the openers

# Use the augmented version of the extract opener
[[opener.extract]]
run = 'ya pub augmented-extract --list "$@"'
desc = "Extract here"
for = "unix"

[[opener.extract]]
run = 'ya pub augmented-extract --list %*'
desc = "Extract here"
for = "windows"

# The Emacs opener
[[opener.emacs]]
run = 'emacs -- "$@"'
block = false
orphan = true
desc = "Open in Emacs"

# The opener to analyse audio spectrums
[[opener.analyse]]
run = 'spek -- "$@"'
block = false
orphan = true
desc = "Analyse spectrum"

# The satty opener
[[opener.satty]]
run = 'satty -f "$0" -o "${0%.*}.png"'
block = false
desc = "Open in Satty"


# Configuration for the opener rules
[[open.prepend_rules]]
url = "*.{el,org,tex,bib}"
use = ["emacs", "edit", "reveal"]

[[open.prepend_rules]]
mime = "text/*"
use = ["edit", "emacs", "reveal"]

[[open.prepend_rules]]
mime = "{audio,video}/*"
use = ["play", "reveal", "analyse"]

[[open.prepend_rules]]
mime = "image/*"
use = ["open", "satty", "reveal"]

# Configuration for the git plugin
[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
