# Keymaps customisation for yazi




# File manager keymaps

# Use the augmented arrow up command for the k key
[[manager.prepend_keymap]]
on   = [ "k" ]
run  = "plugin augment-command --args='arrow -1'"
desc = "Move cursor up"


# Use the augmented arrow down command for the j key
[[manager.prepend_keymap]]
on   = [ "j" ]
run  = "plugin augment-command --args='arrow 1'"
desc = "Move cursor down"


# Use K to move up in the parent directory
[[manager.prepend_keymap]]
on   = [ "K" ]
run  = "plugin augment-command --args='parent-arrow -1'"
desc = "Move cursor up in the parent directory"


# Use J to move down in the parent directory
[[manager.prepend_keymap]]
on   = [ "J" ]
run  = "plugin augment-command --args='parent-arrow 1'"
desc = "Move cursor down in the parent directory"


# Use Ctrl + j to seek 5 units up in the preview pane
[[manager.prepend_keymap]]
on   = [ "<C-j>" ]
run  = "seek -5"
desc = "Seek up 5 units in the preview pane"


# Use Ctrl + k to seek 5 units down in the preview pane
[[manager.prepend_keymap]]
on   = [ "<C-k>" ]
run  = "seek 5"
desc = "Seek down 5 units in the preview pane"

# Use the augmented enter command for the l key
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin augment-command --args='enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <Enter> key
[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin augment-command --args='enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <S-Enter> key
[[manager.prepend_keymap]]
on   = [ "<S-Enter>" ]
run  = "plugin augment-command --args='enter --interactive'"
desc = "Enter the child directory, or open the file interactively"


# Use the augmented enter command for the <Right> key
# but without skipping directories
[[manager.prepend_keymap]]
on   = [ "<Right>" ]
run  = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"


# Use the augmented leave command for the h key
[[manager.prepend_keymap]]
on   = [ "h" ]
run  = "plugin augment-command --args='leave'"
desc = "Go back to the parent directory"


# Use the augmented leave command for the <Left> key
# but without skipping directories
[[manager.prepend_keymap]]
on   = [ "<Left>" ]
run  = "plugin augment-command --args='leave --no-skip'"
desc = "Go back to the parent directory"


# Use the augmented open to open files interactively with O
[[manager.prepend_keymap]]
on   = [ "O" ]
run  = "plugin augment-command --args='open --interactive'"
desc = "Open selected files interactively"


# Use u to unselect and unyank all files
[[manager.prepend_keymap]]
on   = [ "u" ]
run  = ["select_all --state=false", "unyank"]
desc = "Unselect all files and also unyank cut files"


# Use d to cut files
[[manager.prepend_keymap]]
on   = [ "d" ]
run  = "yank --cut"
desc = "Cut the selected files"


# Use p to paste files
[[manager.prepend_keymap]]
on   = [ "p" ]
run  = "plugin augment-command --args='paste'"
desc = "Paste the files"


# Use P to paste files and
# overwrite the destination file if it exists
[[manager.prepend_keymap]]
on   = [ "P" ]
run  = "plugin augment-command --args='paste --force'"
desc = "Paste the files (overwrite if the destination exists)"


# Use _ to create a new file or directory
[[manager.prepend_keymap]]
on   = [ "_" ]
run  = "create"
desc = "Create a file or directory (ends with / for directories)"


# Use + to create a new file or directory
[[manager.prepend_keymap]]
on   = [ "+" ]
run  = "create"
desc = "Create a file or directory (ends with / for directories)"


# Use x to move files to the trash
[[manager.prepend_keymap]]
on   = [ "x" ]
run  = "plugin augment-command --args='remove'"
desc = "Move the files to the trash"


# Use X to delete files permanently
[[manager.prepend_keymap]]
on   = [ "X" ]
run  = "plugin augment-command --args='remove --permanently'"
desc = "Permanently delete the files"


# Use Ctrl + s to open a shell in the current directory
[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"


# Use z to jump to a directory using fzf, since I don't use zoxide
[[manager.prepend_keymap]]
on   = [ "z" ]
run  = "plugin fzf"
desc = "Jump to a directory, or reveal a file using fzf"


# Use o to open files using the editor
[[manager.prepend_keymap]]
on   = [ "o" ]
run  = "plugin augment-command --args='editor'"
desc = "Open files with the default editor"


# Use i to open files using the pager
[[manager.prepend_keymap]]
on   = [ "i" ]
run  = "plugin augment-command --args='pager'"
desc = "Open files with the default pager"


# Use r to rename files with the cursor before the file extension
[[manager.prepend_keymap]]
on   = [ "r" ]
run  = "plugin augment-command --args='rename --cursor=before_ext'"
desc = "Rename a file or directory"


# Use R to remove the whole file name when renaming
[[manager.prepend_keymap]]
on   = [ "R" ]
run  = "plugin augment-command --args='rename --empty=all'"
desc = "Rename file and remove the whole file name"


# Use I to rename files with the cursor at the start of the file name
[[manager.prepend_keymap]]
on   = [ "I" ]
run  = "plugin augment-command --args='rename --cursor=start'"
desc = "Rename file at the start of the file name"


# Use A to rename files with the cursor at the end of the file name
[[manager.prepend_keymap]]
on   = [ "A" ]
run  = "plugin augment-command --args='rename --cursor=end'"
desc = "Rename file with the cursor at the end of the file name"


# Use C to remove the whole file name when renaming
[[manager.prepend_keymap]]
on   = [ "C" ]
run  = "plugin augment-command --args='rename --empty=all'"
desc = "Rename file and remove the whole file name"


# Use cm to remove the file name when renaming
[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "rename --empty=stem --cursor=start"
desc = "Rename file and remove the file name"


# Use ec to go to the config directory for Yazi
[[manager.prepend_keymap]]
on   = [ "e", "c" ]
run  = "cd ~/.config/yazi/"
desc = "Edit the Yazi configuration"


# Use gp to go to the project directory
[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/projects/"
desc = "Go to the projects directory"


# Use gu to go to school directory
[[manager.prepend_keymap]]
on   = [ "g", "u" ]
run  = "cd ~/school/"
desc = "Go to the school directory"




# Selection keymaps

# Use q to close the selection menu
[[select.prepend_keymap]]
on   = [ "q" ]
run  = "close"
desc = "Cancel selection"




# Input keymaps

# Use ^ to move to the beginning of the line, like in vim
[[input.prepend_keymap]]
on   = [ "^" ]
run  = "move -999"
desc = "Move to the BOL"
