# Keymaps customisation for yazi




# File manager keymaps

# Use the smart enter for the l key
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


# Use the smart enter for the <Enter> key
[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


# Use the smart enter for the <Left> key
[[manager.prepend_keymap]]
on   = [ "<Left>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


# Use u to unselect and unyank all files
[[manager.prepend_keymap]]
on   = [ "u" ]
run  = ["select_all --state=false", "unyank"]
desc = "Unselect all files and also unyank cut files"


# Use d to cut files
[[manager.prepend_keymap]]
on   = [ "d" ]
run  = "yank --cut"
desc = "Cut the selected files"


# Use K to move up in the parent directory
[[manager.prepend_keymap]]
on   = [ "K" ]
run  = [ "leave", "escape --visual --select", "arrow -1", "enter" ]
desc = "Move up in the parent directory"


# Use J to move down in the parent directory
[[manager.prepend_keymap]]
on   = [ "J" ]
run  = [ "leave", "escape --visual --select", "arrow 1", "enter" ]
desc = "Move down in the parent directory"


# Use _ to create a new file or directory
[[manager.prepend_keymap]]
on   = [ "_" ]
run  = "create"
desc = "Create a file or directory (ends with / for directories)"


# Use + to create a new file or directory
[[manager.prepend_keymap]]
on   = [ "+" ]
run  = "create"
desc = "Create a file or directory (ends with / for directories)"


# Use x to delete files permanently
[[manager.prepend_keymap]]
on   = [ "x" ]
run  = "remove --permanently"
desc = "Permanently delete the files"


# Use X to move files to the trash
[[manager.prepend_keymap]]
on   = [ "X" ]
run  = "remove"
desc = "Move the files to the trash"


# Use Ctrl + s to open a shell in the current directory
[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"


# Use z to jump to a directory using fzf, since I don't use zoxide
[[manager.prepend_keymap]]
on   = [ "z" ]
run  = "jump fzf"
desc = "Jump to a directory, or reveal a file using fzf"


# Use o to open files using the editor
[[manager.prepend_keymap]]
on   = [ "o" ]
run  = '''
shell "
# Check if the hovered file is selected
if printf '%s\0' \"$@\" | grep -Fxqz -- \"$0\"; then
    $EDITOR $@
else
    $EDITOR $0
fi" --block --confirm
'''
desc = "Open files with the default editor"


# Use i to open files using the pager
[[manager.prepend_keymap]]
on   = [ "i" ]
run  = '''
shell "
# Check if the hovered file is selected
if printf '%s\0' \"$@\" | grep -Fxqz -- \"$0\"; then
    $PAGER $@
else
    $PAGER $0
fi" --block --confirm
'''
desc = "Open files with the default pager"


# Use I to rename files with the cursor at the start of the file name
[[manager.prepend_keymap]]
on   = [ "I" ]
run  = "rename --cursor=start"
desc = "Rename file at the start of the file name"


# Use A to rename files with the cursor at the end of the file name
[[manager.prepend_keymap]]
on   = [ "A" ]
run  = "rename --cursor=end"
desc = "Rename file with the cursor at the end of the file name"


# Use cw to remove the file name when renaming
[[manager.prepend_keymap]]
on   = [ "c", "w" ]
run  = "rename --empty=stem --cursor=start"
desc = "Rename file and remove the file name"


# Use C to remove the whole file name when renaming
[[manager.prepend_keymap]]
on   = [ "C" ]
run  = "rename --empty=all"
desc = "Rename file and remove the whole file name"


# Use R to remove the whole file name when renaming
[[manager.prepend_keymap]]
on   = [ "R" ]
run  = "rename --empty=all"
desc = "Rename file and remove the whole file name"


# Use ec to go to the config directory for yazi
[[manager.prepend_keymap]]
on   = [ "e", "c" ]
run  = "cd ~/.config/yazi/"
desc = "Edit the Yazi configuration"


# Use gp to go to the project directory
[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/projects/"
desc = "Go to the projects directory"


# Use gu to go to school directory
[[manager.prepend_keymap]]
on   = [ "g", "u" ]
run  = "cd ~/school/"
desc = "Go to the school directory"




# Selection keymaps

# Use q to close the selection menu
[[select.prepend_keymap]]
on   = [ "q" ]
run  = "close"
desc = "Cancel selection"




# Input keymaps

# Use ^ to move to the beginning of the line, like in vim
[[input.prepend_keymap]]
on   = [ "^" ]
run  = "move -999"
desc = "Move to the BOL"
