# Schema
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Use the theme that I want
[flavor]
use = "bluloco-dark"

# The theme for the file manager
[manager]

# Remove the borders
border_symbol = " "
