[server]
follow_symlink = false
browser = "default"

[language_servers.pylsp]
enable_pydocstyle = false
enable_flake8 = false
enable_ruff = true
enable_pylint = false
enabled = true
enable_mypy = true
enable_pyflakes = false

[experimental]

[package_management]
manager = "pip"

[snippets]
include_default_snippets = true
custom_paths = []

[formatting]
line_length = 80

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[runtime]
auto_reload = "off"
auto_instantiate = true
std_stream_max_bytes = 1000000
watcher_on_save = "autorun"
output_max_bytes = 8000000
pythonpath = []
on_cell_change = "autorun"

[ai]
rules = ""

[completion]
activate_on_typing = true
copilot = false

[display]
theme = "light"
code_editor_font_size = 14
default_width = "medium"
cell_output = "above"
dataframes = "rich"

[keymap]
preset = "vim"

[keymap.overrides]
